name: Build fastPathSign
on:
  push:
  workflow_dispatch:
jobs:
  Build-fastPathSign:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Build App
       run: |
            g++ *.cpp common/*.cpp -lcrypto -I/usr/local/Cellar/openssl@1.1/1.1.1k/include -L/usr/local/Cellar/openssl@1.1/1.1.1k/lib -O3 -o zsign
