name: Build fastPathSign
on:
  push:
  workflow_dispatch:
jobs:
  Build-fastPathSign:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Build App
       run: |
            make
