name: Build fastPathSign
on:
  push:
  workflow_dispatch:
jobs:
  Build-fastPathSign:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Build App
       run: |
            g++ -c *.cpp common/*.cpp -arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -lcrypto $(pkg-config --cflags libcrypto) -Lexternal/ios
            ls
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add zsign
            git commit -m "Built zsign"
            git push
